import { pbkdf2Sync as nodePbkdf2Sync } from "node:crypto";

const SESSION_COOKIE = "yamamoto_admin_session";
const SESSION_TTL = 60 * 60 * 24 * 7;
const DEFAULT_LINE_ID = "yamamotoauto";
const TEMP_BOOTSTRAP_PASSWORD = "Yamamoto@2026!";
const LEGACY_HASHES = new Set([
  "f7c80072e612e6ea23db65a13b5d0f0b91fd5cbd8f5a059f2d46239cfb8fbab6",
  "1b7b5a2cd58880fa3c76a7c5d6715ea1a16f84cbacd45a9885bee95e9f7af6f9"
]);
const ADMINS = [
  { email: "fujim2021@gmail.com", hash: "f7c80072e612e6ea23db65a13b5d0f0b91fd5cbd8f5a059f2d46239cfb8fbab6", salt: "bcc5d685a3e4bfd08ab56cd991da3818" },
  { email: "nawodyasrajapaksha@gmail.com", hash: "1b7b5a2cd58880fa3c76a7c5d6715ea1a16f84cbacd45a9885bee95e9f7af6f9", salt: "4b4ffe6b65672553f1e8e99942cc9f0b" }
];
const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,OPTIONS", "Access-Control-Allow-Headers": "Content-Type" };
let schemaPromise = null;
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8",...extra}})}
function nowIso(){return new Date().toISOString()}
function getCookie(request,name){for(const part of(request.headers.get("Cookie")||"").split(";")){const[key,...value]=part.trim().split("=");if(key===name)return decodeURIComponent(value.join("="))}return null}
function parseJson(value,fallback){try{return JSON.parse(value)}catch{return fallback}}
function hex(bytes){return[...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function sha256(value){return hex(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))}
function pbkdf2(password,salt,iterations=100000){return nodePbkdf2Sync(password,salt,iterations,32,"sha256").toString("hex")}
async function ensureSchema(env){
  if(schemaPromise)return schemaPromise;
  schemaPromise=(async()=>{
    await env.DB.prepare(`CREATE TABLE IF NOT EXISTS yamamoto_products_v2 (id TEXT PRIMARY KEY,title TEXT NOT NULL,category TEXT,description TEXT,video_url TEXT,price_mode TEXT DEFAULT 'contact',price TEXT,status TEXT DEFAULT 'draft',featured INTEGER DEFAULT 0,images_json TEXT DEFAULT '[]',specs_json TEXT DEFAULT '[]',line_id TEXT,created_at TEXT,updated_at TEXT)`).run();
    await env.DB.prepare(`CREATE TABLE IF NOT EXISTS yamamoto_admins_v2 (email TEXT PRIMARY KEY,password_hash TEXT NOT NULL,salt TEXT NOT NULL,created_at TEXT)`).run();
    await env.DB.prepare(`CREATE TABLE IF NOT EXISTS yamamoto_admin_state_v1 (email TEXT PRIMARY KEY,must_change_password INTEGER NOT NULL DEFAULT 1)`).run();
    await env.DB.prepare(`CREATE TABLE IF NOT EXISTS yamamoto_sessions_v2 (token TEXT PRIMARY KEY,email TEXT NOT NULL,expires_at INTEGER NOT NULL,created_at TEXT NOT NULL)`).run();
    await env.DB.prepare(`CREATE TABLE IF NOT EXISTS yamamoto_admin_bootstrap_v1 (id INTEGER PRIMARY KEY CHECK(id=1),created_at TEXT NOT NULL)`).run();
    for(const a of ADMINS){
      await env.DB.prepare("INSERT OR IGNORE INTO yamamoto_admins_v2(email,password_hash,salt,created_at) VALUES(?,?,?,?)").bind(a.email,a.hash,a.salt,nowIso()).run();
      await env.DB.prepare("INSERT OR IGNORE INTO yamamoto_admin_state_v1(email,must_change_password) VALUES(?,1)").bind(a.email).run();
    }
    await env.DB.prepare("INSERT OR IGNORE INTO yamamoto_admin_bootstrap_v1(id,created_at) VALUES(1,?)").bind(nowIso()).run();
  })().catch(error=>{schemaPromise=null;throw error});
  return schemaPromise;
}
function productView(row){return{id:row.id,title:row.title,category:row.category||"ミニショベル",description:row.description||"",videoUrl:row.video_url||"",priceMode:row.price_mode||"contact",price:row.price||"",status:row.status||"draft",featured:Boolean(row.featured),images:parseJson(row.images_json,[]),specs:parseJson(row.specs_json,[]),lineId:row.line_id||DEFAULT_LINE_ID,createdAt:row.created_at,updatedAt:row.updated_at}}
async function getProduct(env,id,includeDraft=false){const row=await env.DB.prepare("SELECT * FROM yamamoto_products_v2 WHERE id=?").bind(id).first();if(!row||(!includeDraft&&!['published','sold'].includes(row.status)))return null;return productView(row)}
async function listProducts(env,includeDraft=false){const sql=includeDraft?"SELECT * FROM yamamoto_products_v2 ORDER BY CASE status WHEN 'published' THEN 0 WHEN 'draft' THEN 1 WHEN 'sold' THEN 2 ELSE 9 END, updated_at DESC":"SELECT * FROM yamamoto_products_v2 WHERE status IN ('published','sold') ORDER BY CASE status WHEN 'published' THEN 0 WHEN 'sold' THEN 1 ELSE 9 END, updated_at DESC";const{results}=await env.DB.prepare(sql).all();return(results||[]).map(productView)}
async function verifyAdmin(request,env){const token=getCookie(request,SESSION_COOKIE);if(!token)return null;return await env.DB.prepare("SELECT a.email,a.email AS name,COALESCE(st.must_change_password,1) AS must_change_password,s.expires_at FROM yamamoto_sessions_v2 s JOIN yamamoto_admins_v2 a ON a.email=s.email LEFT JOIN yamamoto_admin_state_v1 st ON st.email=a.email WHERE s.token=? AND s.expires_at>? ").bind(await sha256(token),Date.now()).first()||null}
async function requireAdmin(request,env){const admin=await verifyAdmin(request,env);return admin?{admin}:{response:json({error:"ログインが必要です。"},401)}}
function slugify(title){const s=String(title||"machine").normalize("NFKD").replace(/[^a-zA-Z0-9]+/g,"-").replace(/^-+|-+$/g,"").toLowerCase();return(s||"machine")+"-"+Date.now().toString(36)}
function payload(body){body=body||{};return{title:String(body.title||"").trim(),category:String(body.category||"ミニショベル").trim()||"ミニショベル",description:String(body.description||"").trim(),videoUrl:String(body.videoUrl||"").trim(),priceMode:["show","contact"].includes(body.priceMode)?body.priceMode:"contact",price:String(body.price||"").trim(),status:["published","draft","sold"].includes(body.status)?body.status:"draft",featured:Boolean(body.featured),images:Array.isArray(body.images)?body.images.filter(x=>typeof x==="string").slice(0,30):[],specs:Array.isArray(body.specs)?body.specs.filter(x=>x&&x.key).slice(0,40).map(x=>({key:String(x.key).trim(),value:String(x.value||"").trim()})).filter(x=>x.key):[],lineId:String(body.lineId||DEFAULT_LINE_ID).trim()||DEFAULT_LINE_ID}}
async function login(request,env){const body=await request.json().catch(()=>({}));const email=String(body.email||"").trim().toLowerCase(),password=String(body.password||"");if(!email||!password)return json({error:"メールアドレスとパスワードを入力してください。"},400);const admin=await env.DB.prepare("SELECT email,password_hash,salt FROM yamamoto_admins_v2 WHERE lower(email)=? LIMIT 1").bind(email).first();if(!admin)return json({error:"メールアドレスまたはパスワードが正しくありません。"},401);let hash=pbkdf2(password,admin.salt);let bootstrap=false;if(hash!==admin.password_hash&&LEGACY_HASHES.has(admin.password_hash)&&password===TEMP_BOOTSTRAP_PASSWORD){hash=pbkdf2(TEMP_BOOTSTRAP_PASSWORD,admin.salt);await env.DB.prepare("UPDATE yamamoto_admins_v2 SET password_hash=? WHERE email=?").bind(hash,admin.email).run();bootstrap=true;}if(hash!==admin.password_hash&&!(bootstrap&&hash===pbkdf2(TEMP_BOOTSTRAP_PASSWORD,admin.salt)))return json({error:"パスワードが正しくありません。もう一度入力してください。"},401);const token=crypto.randomUUID()+crypto.randomUUID().replace(/-/g,"");await env.DB.prepare("INSERT OR REPLACE INTO yamamoto_sessions_v2(token,email,expires_at,created_at) VALUES(?,?,?,?)").bind(await sha256(token),admin.email,Date.now()+SESSION_TTL*1000,nowIso()).run();const state=await env.DB.prepare("SELECT must_change_password FROM yamamoto_admin_state_v1 WHERE email=?").bind(admin.email).first();return json({email:admin.email,name:admin.email,mustChangePassword:bootstrap||Boolean(state?.must_change_password??1)},200,{"Set-Cookie":`${SESSION_COOKIE}=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${SESSION_TTL}`})}
async function changePassword(request,env){const auth=await requireAdmin(request,env);if(auth.response)return auth.response;const body=await request.json().catch(()=>({})),current=String(body.currentPassword||""),next=String(body.newPassword||"");if(next.length<12)return json({error:"新しいパスワードは12文字以上にしてください。"},400);const row=await env.DB.prepare("SELECT email,password_hash,salt FROM yamamoto_admins_v2 WHERE email=?").bind(auth.admin.email).first();if(!row||pbkdf2(current,row.salt)!==row.password_hash)return json({error:"現在のパスワードが正しくありません。"},401);const salt=crypto.randomUUID(),hash=pbkdf2(next,salt);await env.DB.prepare("UPDATE yamamoto_admins_v2 SET password_hash=?,salt=? WHERE email=?").bind(hash,salt,row.email).run();await env.DB.prepare("INSERT OR REPLACE INTO yamamoto_admin_state_v1(email,must_change_password) VALUES(?,0)").bind(row.email).run();return json({ok:true,message:"パスワードを変更しました。"})}
function mediaKey(url){try{const path=new URL(String(url),"https://yamamoto-auto.local").pathname;return path.startsWith("/media/")?decodeURIComponent(path.slice(7)):null}catch{return null}}
async function deleteMediaObjects(env,urls){if(!env.IMAGES||!Array.isArray(urls))return;for(const url of urls){const key=mediaKey(url);if(!key)continue;try{await env.IMAGES.delete(key)}catch(error){console.error("image cleanup failed",key,error)}}}
async function saveProduct(request,env,id=null){const auth=await requireAdmin(request,env);if(auth.response)return auth.response;const p=payload(await request.json().catch(()=>({})));if(!p.title)return json({error:"機械タイトルを入力してください。"},400);const now=nowIso(),productId=id||slugify(p.title);let imagesToDelete=[];if(p.status==="sold"&&p.images.length>5){imagesToDelete=p.images.slice(5);p.images=p.images.slice(0,5)}if(p.featured)await env.DB.prepare("UPDATE yamamoto_products_v2 SET featured=0 WHERE id<>?").bind(productId).run();if(id){const exists=await env.DB.prepare("SELECT id FROM yamamoto_products_v2 WHERE id=?").bind(id).first();if(!exists)return json({error:"機械が見つかりません。"},404);await env.DB.prepare("UPDATE yamamoto_products_v2 SET title=?,category=?,description=?,video_url=?,price_mode=?,price=?,status=?,featured=?,images_json=?,specs_json=?,line_id=?,updated_at=? WHERE id=?").bind(p.title,p.category,p.description,p.videoUrl,p.priceMode,p.price,p.status,p.featured?1:0,JSON.stringify(p.images),JSON.stringify(p.specs),p.lineId,now,id).run()}else{await env.DB.prepare("INSERT INTO yamamoto_products_v2(id,title,category,description,video_url,price_mode,price,status,featured,images_json,specs_json,line_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(productId,p.title,p.category,p.description,p.videoUrl,p.priceMode,p.price,p.status,p.featured?1:0,JSON.stringify(p.images),JSON.stringify(p.specs),p.lineId,now,now).run()}await deleteMediaObjects(env,imagesToDelete);return json({product:await getProduct(env,productId,true)},id?200:201)}
async function upload(request,env){const auth=await requireAdmin(request,env);if(auth.response)return auth.response;if(!env.IMAGES)return json({error:"画像ストレージが設定されていません。"},500);const form=await request.formData(),files=form.getAll("images").filter(x=>x instanceof File),urls=[];for(const file of files.slice(0,30)){if(!file.type.startsWith("image/")||file.size>15*1024*1024)continue;const ext=(file.name.split(".").pop()||"jpg").replace(/[^a-zA-Z0-9]/g,"")||"jpg",key=`products/${crypto.randomUUID()}.${ext}`;await env.IMAGES.put(key,file.stream(),{httpMetadata:{contentType:file.type,cacheControl:"public,max-age=31536000,immutable"}});urls.push(`/media/${encodeURIComponent(key)}`)}return json({urls})}
async function api(request,env,url){const path=url.pathname;if(request.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders});if(path==="/api/health")return json({ok:true,database:Boolean(env.DB),storage:Boolean(env.IMAGES)});if(path.startsWith("/api/"))await ensureSchema(env);if(path==="/api/login"&&request.method==="POST")return login(request,env);if(path==="/api/logout"&&request.method==="POST"){const token=getCookie(request,SESSION_COOKIE);if(token)await env.DB.prepare("DELETE FROM yamamoto_sessions_v2 WHERE token=?").bind(await sha256(token)).run();return json({ok:true},200,{"Set-Cookie":`${SESSION_COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`})}if(path==="/api/admin/me"){const a=await verifyAdmin(request,env);return a?json({email:a.email,name:a.name||a.email,mustChangePassword:Boolean(a.must_change_password)}):json({error:"ログインが必要です。"},401)}if(path==="/api/admin/password"&&request.method==="POST")return changePassword(request,env);if(path==="/api/setup/admins"&&request.method==="POST")return json({error:"初回設定は不要です。2つの管理者アカウントは既に設定されています。"},400);if(path==="/api/admin/accounts"||path==="/api/admin/accounts/save")return json({error:"この設定は無効になりました。各管理者は自分のパスワードだけ変更できます。"},403);if(path==="/api/products"&&request.method==="GET")return json(await listProducts(env));let match=path.match(/^\/api\/products\/([^/]+)$/);if(match&&request.method==="GET"){const p=await getProduct(env,decodeURIComponent(match[1]));return p?json(p):json({error:"機械が見つかりません。"},404)}if(path==="/api/admin/products"&&request.method==="GET"){const auth=await requireAdmin(request,env);if(auth.response)return auth.response;return json(await listProducts(env,true))}if(path==="/api/admin/products"&&request.method==="POST")return saveProduct(request,env);if(path==="/api/admin/upload"&&request.method==="POST")return upload(request,env);match=path.match(/^\/api\/admin\/products\/([^/]+)$/);if(match){const id=decodeURIComponent(match[1]);if(request.method==="PUT")return saveProduct(request,env,id);if(request.method==="DELETE"){const auth=await requireAdmin(request,env);if(auth.response)return auth.response;const result=await env.DB.prepare("DELETE FROM yamamoto_products_v2 WHERE id=?").bind(id).run();return result.meta?.changes?json({ok:true}):json({error:"機械が見つかりません。"},404)}}if(path.startsWith("/media/")){if(!env.IMAGES)return new Response("",{status:404});const key=decodeURIComponent(path.slice(7)),object=await env.IMAGES.get(key);if(!object)return new Response("",{status:404});return new Response(object.body,{headers:{"Content-Type":object.httpMetadata?.contentType||"application/octet-stream","Cache-Control":"public,max-age=31536000,immutable"}})}return env.ASSETS.fetch(request)}
export default {async fetch(request,env){try{return await api(request,env,new URL(request.url))}catch(error){console.error(error);return json({error:"サーバーエラーが発生しました。"},500)}}};
